### ISSUE TITLE
Module should allow to write to stream

### ISSUE THREAD

**Issue by SBoudrias** [sindresorhus/cli-cursor#1]
Right now this module writes directly to `process.stdout`. I believe it'd be better if it wrote to a given stream.

**Comment by sindresorhus** [comment]
Why? The cursor is only on `stdout`. What's your use-case?

**Comment by SBoudrias** [comment]
This is true, but having it on a custom stream could allow you to pipe the output somewhere else, and ease testing in isolation.

I'm actually not sure how much it'll actually help, I'm still toying around concepts to easily test cli programs.

**Comment by sindresorhus** [comment]
This was fixed in https://github.com/sindresorhus/cli-cursor/commit/750b9a5563608473e62634bcb79f543c3ed78f02.
